<?php

/* custom routes generated by CRUD */
Route::group(['middleware' => ['web']], function () {    
    Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {
        Route::any('sanpham/getAjax', array('as' => 'admin.sanpham.getAjax', 'uses' => 'SanPhamController@getAjax'));
        Route::any('sanpham/saveSp', array('as' => 'admin.sanpham.saveSp', 'uses' => 'SanPhamController@saveSp'));
        Route::resource('sanpham', 'SanPhamController');
        Route::get('sanpham/{id}/delete', array('as' => 'admin.sanpham.delete', 'uses' => 'SanPhamController@getDelete'));
        Route::get('sanpham/{id}/confirm-delete', array('as' => 'admin.sanpham.confirm-delete', 'uses' => 'SanPhamController@getModalDelete'));
    });
    
//    Ban
    Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {
        Route::any('ban/getAjax', array('as' => 'admin.ban.getAjax', 'uses' => 'BanController@getAjax'));
        Route::any('ban/saveSp', array('as' => 'admin.ban.save', 'uses' => 'BanController@saveBan'));
        Route::resource('ban', 'BanController');
        Route::get('ban/{id}/delete', array('as' => 'admin.ban.delete', 'uses' => 'BanController@getDelete'));
        Route::get('ban/{id}/confirm-delete', array('as' => 'admin.ban.confirm-delete', 'uses' => 'BanController@getModalDelete'));
    });
    
    //Chi
    Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {
        Route::any('chi/getAjax', array('as' => 'admin.chi.getAjax', 'uses' => 'ChiController@getAjax'));
        Route::any('chi/saveSp', array('as' => 'admin.chi.save', 'uses' => 'ChiController@saveChi'));
        Route::resource('chi', 'ChiController');
        Route::get('chi/{id}/delete', array('as' => 'admin.chi.delete', 'uses' => 'ChiController@getDelete'));
        Route::get('chi/{id}/confirm-delete', array('as' => 'admin.chi.confirm-delete', 'uses' => 'ChiController@getModalDelete'));
    });
    
    //HoaDon
    Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {
        Route::any('hoadon/getAjax', array('as' => 'admin.hoadon.getAjax', 'uses' => 'HoaDonController@getAjax'));
        Route::any('hoadon/saveHoaDon', array('as' => 'admin.hoadon.save', 'uses' => 'HoaDonController@saveHoaDon'));
        Route::resource('hoadon', 'HoaDonController');
        Route::get('hoadon/{id}/delete', array('as' => 'admin.hoadon.delete', 'uses' => 'HoaDonController@getDelete'));
        Route::get('hoadon/{id}/confirm-delete', array('as' => 'admin.hoadon.confirm-delete', 'uses' => 'HoaDonController@getModalDelete'));
    });
});

